//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 FinishCS.rc 使用
//
#define IDD_DIALOG_PIPELINEJBXX         1
#define IDD_DIALOG_PIPELINEMODIFYPROJECTINFO 2
#define IDD_DIALOG_PipiConfig           3
#define IDD_DIALOG_PIPELINEROADINFO     4
#define IDD_DIALOG_GHSSJBQKINFODLG      4
#define IDD_DIALOG_DRAWDZX              5
#define IDD_DIALOG_WRITELCHFILE         6
#define IDD_DIALOG_HDMCREATE            7
#define IDD_DIALOG_PROJECTINFO          8
#define IDD_DIALOG_FLOORINFO            9
#define IDD_DIALOG_XMJGFUNCTIONDEFINE   10
#define IDD_DIALOG_XMJG_CHANGELAYERINFO 11
#define IDD_DIALOGXMJGCOMPRESSDLG       12
#define IDD_DIALOG_CHANGECARPRO         13
#define IDD_DIALOG_XMJG_PROJECTBASEINFOSETTINGDLG 14
#define IDD_DIALOG_SETSTRATIFINCATIONPLANINFO 15
#define IDD_DIALOG_FUNCTIONALAREAS      16
#define IDD_DIALOG_OPENPROJECTDLG       17
#define IDD_DIALOG_XMJG_PROJECTPROMPTDLG 18
#define IDD_DIALOG_XMJG_PROJECTAREASETTINGDLG 19
#define IDD_DIALOG_ZONGDUAN             20
#define IDD_DIALOG4                     24
#define IDD_DIALOG_TDOPOM               25
#define IDD_DIALOG_SETHANDLEPIPELINEDLG 26
#define IDD_DIALOG_EXPORTPIPEZPTS       27
#define IDD_DIALOG_PIPELINECREATE       28
#define IDD_DIALOG_PIPELINEOUTPUT       29
#define IDD_DIALOG_PIPELINESELECTOUTPUT 30
#define IDD_DIALOG_PIPELINESELECT       31
#define IDD_DIALOG_PIPELINECREATEPROJECT 32
#define IDD_DIALOG_DEFICIENCYFILESDLG   33
#define IDD_DIALOG_SUBCOMPRESSDLG       34
#define IDD_DIALOG_XMJG_EXPORTINFODLG   35
#define IDD_DIALOG_XMJG_PROJECTEXPORTDOCSETTINGDLG 36
#define IDD_DIALOG_XMJGCOMPRESSDLG      37
#define IDD_DIALOG_XMJG_SETLAYERINFODLG 38
#define IDD_DIALOG_PROJECTEXPORTRESULTDOCDLG 39
#define IDD_DIALOG_XMJG_PROJECTEXPORTRESULTDOCDLG 40
#define IDD_DIALOG_EXTENT_BUILDING      41
#define IDD_DIALOG_MATCHEX              42
#define IDD_DIALOG_INDOORSURVEY_NOTE    43
#define IDD_DIALOG_TEST                 44
#define IDD_DIALOG_DRAWTHINGS           46
#define IDD_DIALOG_ENTITYS_LIST         47
#define IDD_DIALOG_EXTRACTDLG           48
#define IDD_DIALOG_RESULTS_CHECK_WIZARD 49
#define IDD_DIALOG_INDOORSURVEY_NOTE1   50
#define IDD_DIALOG_INDOORSURVEY_NOTE_STANDARD2 51
#define IDC_HDMCREATE_MIDDLE1           52
#define IDC_DZX_DELTZ_TXT2              53
#define IDC_BUTTON1                     54
#define IDC_DZX_SINGLE_TXT2             55
#define IDC_DZX_SMGC_TXT2               56
#define IDC_DZX_SMGC_TXT1               57
#define IDC_DZX_DELTZ_TXT1              58
#define IDC_DZX_SINGLE_TXT1             59
#define IDC_DRAWDZX_STATIC2             60
#define IDC_DRAWDZX_STATIC1             61
#define IDC_DZX_NIHE4                   62
#define IDC_DZX_NIHE3                   63
#define IDC_DZX_NIHE2                   64
#define IDC_DZX_TOLERANCE               65
#define IDC_DZX_STEP                    66
#define IDC_DZX_TOLERANCE_TXT           67
#define IDC_DZX_STEP_TXT                68
#define IDC_DZX_SMGC                    69
#define IDC_DZX_SINGLEH                 70
#define IDC_DZX_SINGLE                  71
#define IDC_DZX_NIHE1                   72
#define IDC_DZX_MINH                    73
#define IDC_DZX_MAXH                    74
#define IDC_DZX_DELTZ                   75
#define IDC_LCHFILE_FILETIP             77
#define IDC_LCHFILE_TYPE2               78
#define IDC_LCHFILE_DATBROWSE           79
#define IDC_LCHFILE_LCHBROWSE           80
#define IDC_LCHFILE_GCDBROWSE           81
#define IDC_LCHFILE_TYPE3               82
#define IDC_LCHFILE_JIAODIAN            83
#define IDC_LCHFILE_CHAZHI              84
#define IDC_LCHFILE_TYPE1               85
#define IDC_LCHFILE_EXCEL               86
#define IDC_LCHFILE_LCZMC               87
#define IDC_LCHFILE_DIST                89
#define IDC_LCHFILE_GCDFILE             90
#define IDC_HDMCREATE_LEFT              93
#define IDC_HDMCREATE_RIGHT             94
#define IDC_HDMCREATE_STEP              95
#define IDC_HDMCREATE_M_diLE1           96
#define IDC_HDMCREATE_MIDDLE2           97
#define IDC_HDMCREATE_MIDDLE3           98
#define IDC_HDMCREATE_START             99
#define IDS_PROJNAME                    100
#define IDD_PROPPAGE_WIZARD_SELECT_TYPE 106
#define IDC_LIST1                       200
#define IDC_BUTTON_STATIC               202
#define IDC_LIST_STATICINFO             203
#define IDC_BUTTON_SELECT               204
#define IDC_BUTTON_NOTE                 205
#define IDC_STATIC_BUILDING_NO          206
#define IDC_STATIC_FLOOR_INFO           207
#define IDC_BUTTON_CACULATE_AREA        208
#define IDC_LIST_STATIC_TEXT            209
#define IDC_LIST_MAIN                   210
#define IDC_BUTTON_POSITION             210
#define IDC_LIST_NOTE_TYPE2             211
#define IDC_EDIT_COUNT                  212
#define IDC_EDIT_LENGTH                 213
#define IDD_PROPPAGE_WIZARD_SELECT_PATH 213
#define IDD_PROPPAGE_WIZARD_EXPORT_RESULT 214
#define IDC_EDIT_LENGTH2                214
#define IDC_EDIT_HEIGH                  214
#define IDC_LIST_NOTE_TYPE              215
#define IDC_STATIC_COUNT                216
#define IDC_STATIC_LENGTH               217
#define IDC_STATIC_LENGTH2              218
#define IDD_XMJEXPORTINFO2              218
#define IDC_EDIT_TEXT_SIZE              219
#define IDC_EDIT_COUNT2                 219
#define IDC_EDIT_SPAN                   219
#define IDD_CONTROLPOINTATTRIBUTE       219
#define IDC_STATIC_COUNT2               220
#define IDD_XMJGPLAN                    220
#define IDC_MFCPROPERTYGRID1            221
#define IDC_STATIC_LENGTH3              221
#define IDC_MFCSHELLTREE1               222
#define IDC_MFCSHELLLIST1               223
#define IDC_EDIT_COUNT3                 223
#define IDC_EDIT_DEEP                   223
#define IDC_MFCMENUBUTTON1              224
#define IDC_STATIC_COUNT3               224
#define IDD_XMJGREDLINEQUALITY          224
#define IDC_MFCMASKEDEDIT1              225
#define IDC_STATIC_LENGTH4              225
#define IDC_MFCFONTCOMBO1               226
#define IDC_EDIT_LENGTH3                226
#define IDC_EDIT_WELL_DIAMETER          226
#define IDD_XMJG_SETPROJECTCODE         226
#define IDC_MFCVSLISTBOX1               227
#define IDC_EDIT_COUNT4                 227
#define IDC_EDIT_TREE_DIAMETER          227
#define IDD_XMJG_LINCESEDOCDLG          227
#define IDC_MFCEDITBROWSE1              228
#define IDC_STATIC_COUNT4               228
#define IDD_XMJG_CHANGEPICTUREPROPERTY  228
#define IDC_MFCCOLORBUTTON1             229
#define IDD_XMJGSETINFO7                229
#define IDC_NETADDRESS1                 230
#define IDD_XMJGPROJECTINFO             230
#define IDC_COMMAND1                    231
#define IDD_XMJGSETINFO2                231
#define IDC_MFCLINK1                    232
#define IDC_BUTTON_SELECT_BUILDING      233
#define IDC_BUTTON_COMBINE_TO_MAIN      234
#define IDC_BUTTON_COMBINE_TO_ATTACHMENT 235
#define IDC_EDIT_EXTENT_DIST            236
#define IDC_BUTTON_SPLASH               237
#define IDC_BUTTON_SELECT_BUILDING2     237
#define IDC_BUTTON_CLEAR_RESULT         237
#define IDC_BUTTON_PREVIOUS             237
#define IDC_BUTTON_BROWSE1              237
#define IDC_SELECTFILE                  237
#define IDC_XMJGMOVEUP                  237
#define IDC_DISTANCE                    237
#define IDC_BUTTONXMJG_DEL              237
#define IDC_BUTTON_XMJGADD              237
#define IDC_BUTTON_DELETE_OLD_BUILDING  238
#define IDC_RICHEDIT21                  238
#define IDC_BUTTON_BROWSE2              238
#define IDC_EDIT_MAINTEXT               239
#define IDC_BUTTON_BROWSE3              239
#define IDC_CHECK_SELECTALL             240
#define IDC_BUTTON5                     240
#define IDC_BUTTON_BROWSE4              240
#define IDC_BUTTON_ADDLAYER             240
#define IDC_CHECK_UNSELECT              241
#define IDC_RADIO1                      242
#define IDC_RADIO_FRAME_SCALE           242
#define IDC_ISMAINFLOOR                 242
#define IDC_RADIO_XMJG_LSSSSFCC1        242
#define IDC_RADIO_LOCATION_PL           242
#define IDC_RADIO2                      243
#define IDC_RADIO3                      244
#define IDC_BUTTON2                     245
#define IDC_BUTTON_NEXT                 245
#define IDC_XMJGMOVETOP                 245
#define IDC_BETWEEN                     245
#define IDC_BUTTONXMJG_ADD              245
#define IDC_BUTTON_XMJGDEL              245
#define IDC_BUTTON_COMPRESSREVERSE      245
#define IDC_BUTTONADD                   245
#define IDC_BUTTON_RSELECT              245
#define IDC_BUTTON_REVERSESELECT        245
#define IDC_STATIC_WIZ_FRAME            246
#define IDC_EDIT_FEATURE_TABLE          247
#define IDC_LIST_CHECK_TYPE             248
#define IDC_EDIT_BUILDING_AREA_FRAME    248
#define IDC_EDIT_SUMMARY_TABLE          249
#define IDC_EDIT_TOTAL_FRAME            250
#define IDC_NUMBER                      252
#define IDC_BUILDPROJECT                254
#define IDC_MEASUREMENTCONTENT          256
#define IDC_TELEPHONE                   257
#define IDC_XMJG_PROJECTNAME2           268
#define IDC_XMJG_BUILDCOMPANY2          269
#define IDC_XMJG_PROJECTADDRESS2        270
#define IDC_XMJG_AREA2                  272
#define IDC_XMJG2_PROJECTSTREET         273
#define IDC_XMJG_STREET2                274
#define IDC_XMJG2_PROJECTLOAD           275
#define IDC_XMJG_ROAD2                  276
#define IDC_EDIT1                       282
#define IDC_ACCEPTCODE7                 282
#define IDC_INPUTINFO2                  282
#define IDC_ACCEPTCODE2                 282
#define IDC_BUILDAREA                   282
#define IDC_BUILDAREA5                  282
#define IDC_EDITXMJG_MJXS               282
#define IDC_FUNCTIONSMAINHEIGHT         282
#define IDC_EDITPISACCEPTANCECODE       282
#define IDC_EDIT_XMJG1PROJECTCONTECT    282
#define IDC_EDIT_XMJGGHTHXJJ            282
#define IDC_EDIT_PROJECTDIR3            282
#define IDC_EDIT_PROJECTDIR4            282
#define IDC_EDIT_PROJECTDIR6            282
#define IDC_EDIT_ADSGHJRMJ              282
#define IDC_EDIT_XMJGCOMPRESSCODE       282
#define IDC_EDIT_SLI_BUILDNAME          282
#define IDD_XMJGSETINFO1                283
#define IDC_EDIT3                       283
#define IDC_XMJBXXCHDW                  284
#define IDD_XMJGSETINFO3                285
#define IDC_INPUTINFO5                  285
#define IDD_XMJGSETINFO4                286
#define IDD_XMJGSETINFO5                287
#define IDC_ACCEPTCODE1                 288
#define IDC_ENTRUSTCOMPANY1             289
#define IDC_BUILDPROJECT1               290
#define IDC_PROJECTNAME1                291
#define IDC_MEANSURECONTEXT1            292
#define IDC_ENTRUSTCODE2                294
#define IDC_EXTERIORWALL2               301
#define IDC_BUILDAXIS2                  302
#define IDC_COMBO1                      306
#define IDC_CONTROLPOINTRANK            306
#define IDC_SELECTINPUTTITLE2           306
#define IDC_COMBOXMJG_FUNCTIONNAME      306
#define IDC_COMBO_XMJGBUILDNAME         306
#define IDC_COMBO_TJLOCATION            306
#define IDC_COMBO2                      307
#define IDC_CONTROLOINTTYPE             307
#define IDC_CONTROLPOINTTYPE            307
#define IDC_MEANSURECOMPANY7            307
#define IDC_COMBO_AREAFACTOR            307
#define IDC_ACCEPTCODE3                 308
#define IDC_PROJECTADDRESS3             309
#define IDC_FLOORLIST                   309
#define IDC_BUILDPROJECT3               310
#define IDC_EDIT7                       310
#define IDC_EDITPISLICENSEDOCS          310
#define IDC_EDIT_XMJGGHQTGHYQ           310
#define IDC_EDIT_SLI_NVWALLHEIGHT       310
#define IDC_EDIT_XMJG_PBQTXYSMDQK       310
#define IDC_XMJBXXYDMJ                  310
#define IDC_PROJECTNAME3                311
#define IDC_JINGBANREN3                 312
#define IDC_LICENESECODE3               313
#define IDC_BUILDAREA3                  314
#define IDC_CHECKCODE3                  315
#define IDC_ACCEPTCODE4                 316
#define IDC_REDLINECOORANN              316
#define IDC_ENTRUSTCOMPANY4             317
#define IDC_CHECK2                      317
#define IDC_NOCROSSREDLINENODEANN       317
#define IDC_CHECK_SLI_XIEWUMIAN         317
#define IDC_CHECK_MATCHPIPL             317
#define IDC_CHECK_AREAKOUCHU            317
#define IDC_BUILDPROJECT4               318
#define IDC_REDLINELENGHTANN            318
#define IDC_PROJECTNAME4                319
#define IDC_REDLINESEGMENTANN           319
#define IDC_ELEVATIONSYSTEM4            320
#define IDC_TELEPHONENUM3               320
#define IDC_TELEPHONE4                  321
#define IDC_PROJECTDIR                  321
#define IDC_SETACCEPTCODE               322
#define IDC_COMPLAINT4                  323
#define IDC_LICENSEDOC                  323
#define IDC_ACCEPTCODE5                 324
#define IDC_BUILDCOMPANY5               325
#define IDC_XMJGPICTUREBROWING          325
#define IDC_PROJECTNAME5                326
#define IDC_XMJGMOVEDOWN                326
#define IDC_PROJECTADD5                 327
#define IDC_XMJGMOVEBUTTOM              327
#define IDC_LICENSECODE5                328
#define IDC_CHECKCODE5                  329
#define IDC_XMJGDELPICTURE              329
#define IDC_INFOMATION5                 330
#define IDC_XMJGADDPIXTURE              330
#define IDD_XMJGSETINFO6                331
#define IDC_BUILDCOMPANY7               331
#define IDC_ACCEPTCODEGPB               332
#define IDC_PROJECTNAME7                332
#define IDC_BUILDCOMPANYGPB             333
#define IDC_PROJECTADDRESS7             333
#define IDC_PROJECTNAMEGPB              334
#define IDC_PROJECTADDGPB               335
#define IDC_SHISHICOMPANY7              335
#define IDC_LICENSECODEGPB              336
#define IDC_PROJECTINFO                 336
#define IDC_CHECKCODEGPB                337
#define IDC_BUILDCOMPANY2               337
#define IDC_INFOMATIONGPB               338
#define IDC_PROJECTNAME2                338
#define IDC_PROJECTADD2                 339
#define IDC_PLANCODE                    340
#define IDC_LICENSECODE2                340
#define IDC_FLOORCODE                   341
#define IDC_BUILDAREA2                  341
#define IDC_EDIT2                       342
#define IDC_EDITXMJG_JRXS               342
#define IDC_EDITPISPROJECTNAME          342
#define IDC_EDIT_XMJGSCTHXJJ            342
#define IDC_EDIT_PROJECTDIR2            342
#define IDC_EDIT2_PROJECTDIR5           342
#define IDC_FLOORHEIGHT                 343
#define IDC_LIST_XMJGLAYERINFO          343
#define IDC_PARAPETWALL                 344
#define IDC_LISTCOMPRESS                344
#define IDC_EDIT49                      344
#define IDC_BUTTON3                     345
#define IDC_BUTTON_COMPRESSADDFILE      345
#define IDC_BUTTON_ASELECT              345
#define IDC_BUTTON_ADDPIPELINE          345
#define IDC_EDIT54                      345
#define IDC_BUTTON_PIPELINENOTSELECT    345
#define IDC_BUTTON_CANCEL               345
#define IDC_BUTTON_ROADHENGDUANMIANADD  345
#define IDC_CHECK1                      346
#define IDC_CHECK_ISJIACENG             346
#define IDC_CHECK_XMJG_LSSSSFCC1        346
#define IDC_CHECK_SLI_PINGWUMIAN        346
#define IDC_EDIT55                      346
#define IDC_CHECK_LOCATIONPL            346
#define IDC_CHECK_MATCHPIPEPOINT        346
#define IDC_CHECK_ISLAND                346
#define IDC_CHECK_SELECTBH              346
#define IDC_EDITPISPROJECTADDRESS       347
#define IDC_EDIT56                      347
#define IDC_FUNCTIONSNAME               348
#define IDC_EDITPISBUILDCOMPANY         348
#define IDC_EDIT57                      348
#define IDC_FUNCTIONSCODE               349
#define IDC_EDITPISMEANSURECOMPANY      349
#define IDC_FUNCTIONSHEIGHT             350
#define IDC_EDITCONDUCECOMPANY          350
#define IDC_AREACOEFFICIENT             351
#define IDC_EDITPISCONTROLPOINT         351
#define IDC_FUNCTIONSFACTOR             352
#define IDC_EDITCONTROLBASEPOINT        352
#define IDC_FUNCTIONSNAMES              353
#define IDC_EDITDETAILSURVEY            353
#define IDC_STATIC1                     354
#define IDC_STATIC2                     355
#define IDC_BUTTON4                     355
#define IDC_BUTTON_DELFILE              355
#define IDC_BUTTON_ROADHENGDUANMIANDEL  355
#define IDC_STATIC3                     356
#define IDC_STATIC4                     357
#define IDC_LIST_DEFICIENCYFILES        357
#define IDC_STATIC5                     358
#define IDC_EDIT_XMJGGHJZJJ             358
#define IDC_STATIC6                     359
#define IDC_EDIT_XMJSCGJZJJ             359
#define IDC_STATIC7                     360
#define IDC_EDIT_XMJGGHJZLMYQ           360
#define IDC_STATIC8                     361
#define IDC_EDIT_XMJSCJZLMYQ            361
#define IDC_STATIC9                     362
#define IDC_EDIT_XMJSCQTGHYQ            362
#define IDC_STATIC10                    363
#define IDC_EDIT_XMJG_YGHXKBYZQK        363
#define IDC_STATIC11                    364
#define IDC_EDIT_XMJG_QTXYSMDQK         364
#define IDC_STATIC12                    365
#define IDC_STATIC13                    366
#define IDC_STATIC14                    367
#define IDC_STATIC15                    368
#define IDC_ZONG_SCALEX                 369
#define IDC_TAB_EXPORTDOC               369
#define IDC_ZONG_SCALEY                 370
#define IDC_RADIO_XMJG_LSSSSFCC2        370
#define IDC_ZONG_PLACEX                 371
#define IDC_ZONG_PLACEY                 372
#define IDC_ZONG_PICK                   373
#define IDC_ZONG_PMTTEXT                374
#define IDC_ZONG_HPMT1                  375
#define IDC_ZONG_HPMT2                  376
#define IDC_ZONG_LCTEXT1                377
#define IDC_ZONG_BEGINLC                378
#define IDC_EDIT11                      378
#define IDC_EDIT_SLI_WDHEIGHT           378
#define IDC_XMJBXXLXR                   378
#define IDC_ZONG_LCTEXT2                379
#define IDC_ZONG_IFBCH                  380
#define IDC_ZONG_BCHTEXT                381
#define IDC_ZONG_BIAOCHI                382
#define IDC_ZONG_LICHENG1               383
#define IDC_ZONG_LICHENG2               384
#define IDC_ZONG_IFFG                   385
#define IDC_ZONG_FGTEXTX                386
#define IDC_EDIT_ADSSCJRMJSM            386
#define IDC_ZONG_FGX                    387
#define IDC_EDIT_ADSGHJRMJSM            387
#define IDC_ZONG_FGTEXTY                388
#define IDC_EDIT_XMJGGHGGJZPT           388
#define IDC_ZONG_FGY                    389
#define IDC_EDIT_XMJGSCGGJZPT           389
#define IDC_ZONG_JGTEXT1                390
#define IDC_ZONG_JGTEXT2                391
#define IDC_BUTTON_COMPRESSALLSELECT    391
#define IDC_IDDelete                    391
#define IDC_ZONG_JGNUM                  392
#define IDC_TAB_XMJGCOMPRESSTAB         392
#define IDC_ZONG_JGTEXT3                393
#define IDC_EDIT_XMJGCOMPRESSNAME       393
#define IDC_ZONG_JGY                    394
#define IDC_EDIT_SLI_SJLAYERHEIGHT      394
#define IDC_ZONG_JGTEXT4                395
#define IDC_EDIT_SLI_SCLAYERHEIGHT      395
#define IDC_ZONG_JGX                    396
#define IDC_EDIT_SLI_SJCONTEXT          396
#define IDC_ZONG_HEIGHT1                397
#define IDC_EDIT_SLI_SCCONTEXT          397
#define IDC_ZONG_HEIGHT2                398
#define IDC_EDIT_SLI_TJHEIGHT           398
#define IDC_ZONG_HEIGHT3                399
#define IDC_ZONG_WIDTH                  400
#define IDC_EDIT_SLI_CWALLHEIGHT        400
#define IDC_ZONG_LCHHIGH                401
#define IDC_EDIT_SLI_ANGLE              401
#define IDC_ZONG_LCHMIN                 402
#define IDC_EDIT_SLI_LAYERNAME          402
#define IDC_ZONG_LCHWEI1                403
#define IDC_ZONG_LCHWEI2                404
#define IDC_ZONG_LCHWEI3                405
#define IDC_COMBOPROCARTYPE             406
#define IDC_EDITPROCARNUM               407
#define IDC_EDITPROCARLAYER             408
#define IDC_COMBOPROBARRIERCAR          409
#define IDC_RADIO_XMJG_DISHANG          410
#define IDC_RADIO_XMJG_DIXIA            411
#define IDC_EDIT_ASDJZYDMJ              420
#define IDC_EDIT_ASDDSCW                421
#define IDC_EDIT_ASDJZMD                422
#define IDC_EDIT_ASDSM                  423
#define IDC_EDIT_ASDDXCW                424
#define IDC_EDIT_ASDSCZYCRKWZ           425
#define IDC_EDIT_ASDGHZYCRKWZ           426
#define IDC_EDIT_ASDGHZJZMJ             427
#define IDC_EDIT_ASDSCZJZMJSM           428
#define IDC_EDIT_ASDGHZJZMJSM           429
#define IDC_EDIT_ASDSCDSMJSM            430
#define IDC_EDIT_ASDGHDSMJ              431
#define IDC_EDIT_ASDSCDXMJSM            432
#define IDC_EDIT_ASDGHDSMJSM            433
#define IDC_EDIT_ASDGHDXMJSM            434
#define IDC_EDIT_ASDGHDXMJ              435
#define IDC_FLOORNUM1                   440
#define IDC_FLOORNUM2                   441
#define IDC_LIST_LAYERINFO              442
#define IDC_PLANADD                     443
#define IDC_PLANDEL                     444
#define IDC_BUTTON_MOVEUP               445
#define IDC_BUTTON_MOVEDOWN             446
#define IDC_XMJG2_PROJECTNAME           447
#define IDC_XMJG2_BUILDCOMPANY          448
#define IDC_XMJG2_PROJECTAREA           449
#define IDC_XMJG2_PROJECTCODE           450
#define IDC_XMJG2_EDGEDISTANCE          451
#define IDC_XMJG2_BUILDDISTANCE         452
#define IDC_XMJG2_SCEDGEDISTANCE        453
#define IDC_XMJG2_SCBUILDDISTANCE       454
#define IDC_BUILDWALL2                  455
#define IDC_BUILDAIXS2                  456
#define IDC_STATIC_PROJECTCODEPROMPT    458
#define IDC_STATIC_PROJECTNAMEPROMPT    459
#define IDC_DATETIMEAPPLY               460
#define IDD_XMJG_BRIDGEANNOTATEDLG      460
#define IDC_DATETIMEPIBAPPLY            461
#define IDC_EDIT_SLI_LAYERBEIZHU        462
#define IDC_LIST3                       465
#define IDC_LIST_PROJECTDWG             467
#define IDC_LIST2                       468
#define IDD_DIALOG_PIPELINEPROPERTYDLG  476
#define IDD_DIALOG_SUBPIPELINEPROPERTYDLG 477
#define IDD_DIALOG_SUBPIPEPOINTPROPERTYDLG 478
#define IDD_DIALOG_PIPELINEOUTPUTPART   479
#define IDD_DIALOG_FILTERLAYERDLG       480
#define IDD_DIALOG_SHIZHENG             481
#define IDD_DIALOG_PIPELINECREATEPROJECT1 482
#define IDD_DIALOG_TQZBINFO             483
#define IDD_DIALOG_TESTSUBDLG           485
#define IDD_DIALOG_SHIZHENGPIPELINE     486
#define IDD_DIALOG_ROADHDMDZTTL         487
#define IDD_DIALOG_LAYERMANAMGER        488
#define IDD_DIALOG_CHAICENGDLG          489
#define IDC_EDIT_PROJECTPATH            490
#define IDD_DIALOGMODIFYPROJECTINFO     490
#define IDC_BUTTON_SELECTPROJECT        491
#define IDD_DIALOG_NEW_LAYERINFO        491
#define IDC_EDIT_SLI_JZMJ               492
#define IDD_DIALOG_QUALITYCHECKREPORT   492
#define IDC_EDIT_SLI_JRMJ               493
#define IDD_DIALOG_QUALITYCHECKSUBREPORT 493
#define IDC_BUTTON_DELETE               494
#define IDD_DIALOG_DRAWUPPLANNING       494
#define IDC_EDITPBPISLICENSEDOCS        495
#define IDD_DIALOG_RECONFIGURATIONDLG   495
#define IDC_EDITPBCONTROLBASEPOINT      496
#define IDD_DIALOG_BRIDGEPROPERTRYDLG   496
#define IDC_EDITPBEXISTINGINFOMATION    497
#define IDD_INFOMATIONOFPROJECTRANGELINE 497
#define IDC_EDITPBTOPOGRAPHICSURVEY     498
#define IDD_DIALOG_DRAWDOMAINDIALOG     498
#define IDC_EDIT_XMJG_PBYGHXKBYZQK      499
#define IDD_DIALOG_                     499
#define IDD_DIALOG_HEIGHTPROPERTYSETTING 499
#define IDC_EDIT_PBOVERPASSMEASUREMENT  500
#define IDC_EDIT_ENTRUSTMENTUNIT        501
#define IDC_LIST_PIPELINE               502
#define IDC_BUTTON_SELECTALL            503
#define IDC_EDIT_BRIDGETYPE             504
#define IDC_LCHFILE_DLMC                513
#define IDC_TAB_PIPELINEPANEL           515
#define IDC_TAB_PIPELINECREATETAB       523
#define IDC_LIST_PIPELINESELECTLIDG     528
#define IDC_BUTTON_PIPELINESELECTALL    529
#define IDC_BUTTON_PIPELINEREVERSESELECT 530
#define IDC_LIST_PROJECTINFO            536
#define IDC_TAB_PIPELINEPROPERTY        537
#define IDC_LIST_PIPELINEPROPERTY       538
#define IDC_LIST_PIPEPOINTPROPERTY      539
#define IDC_BUTTON_PIPEPOINTFLUSHAPROPERTY 540
#define IDC_BUTTON_PIPEPOINTLOCATION    541
#define IDC_BUTTON_PIPEPOINTREASSOCIATE 542
#define IDC_EDIT_PIPELINEBUILDPROJECT   543
#define IDC_EDIT_PIPELINEBUILDAREA      544
#define IDC_LIST_PLOUTPUTPART           545
#define IDC_BUTTON_PIPELINEREFLASHTABLE 546
#define IDC_BUTTON_PIPELINECORRELATIONENTITY 547
#define IDC_COMBO_PIPELINE              548
#define IDC_LIST_FILTERLAYER            549
#define IDC_BUTTON_IMPORTALL            550
#define IDC_BUTTON_PIPELINEREVERSE      551
#define IDC_TAB_PIPELINECREATETAB1      551
#define IDC_COMBO_PIPELINEGXLX          552
#define IDC_RADIO_LOCATIONPP            553
#define IDC_BUTTON_PICK                 554
#define IDC_BUTTON_PICKPOINT            554
#define I                               554
#define IDC_BUTTON_EXPORT               554
#define IDC_DATETIMEPICKER1             555
#define IDC_DATETIMEPICKER_SZXM         556
#define IDC_COMBO_ROADNAME              557
#define IDC_BUTTON_ROADPINGMIANADD      559
#define IDC_BUTTON_ROADPINGMIANDEL      560
#define IDC_BUTTON_ROADZONGDUANMIANADD  561
#define IDC_BUTTON_ROADZONGDUANMIANDEL  562
#define IDC_COMBO_SZPIPELINETYPE        563
#define IDC_LIST_SZPIPELINEINFO         564
#define IDC_BUTTON_PIPELINETYPEADD      565
#define IDC_BUTTON_PIPELINETYPEDEL      566
#define IDC_BUTTON_SELECTENT            567
#define IDC_BUTTON_DELETEITEM           568
#define IDC_LIST_ROADDZTLIST            569
#define IDC_EDIT_INSERTDWGSCALE         570
#define IDC_EDIT2_TINAME                571
#define IDC_DATETIMEPICKER_EXPORT       572
#define IDC_EDIT_EXPORTTIME             573
#define IDC_EDIT_DPROJECTNAME           574
#define IDC_EDIT_DPROJECTCODE           575
#define IDC_EDIT_MPROJECTNAME           577
#define IDC_EDIT_MPROJECTCODE           578
#define IDC_LIST_PROJECTNAMES           580
#define IDC_EDIT_ASDSCJZYDMJSM          582
#define IDC_LIST_LAYERINFOLISTS         583
#define IDC_BUTTON_COPYLAYER            584
#define IDC_BUTTON_DELLAYER             585
#define IDC_TAB_QUALITYCHECKREPORT      587
#define IDC_EDIT_QUALITYCHECKCONTEXT    588
#define IDC_BUTTON_SPLITLAYER           589
#define IDC_BUTTON_MAGERLAYER           590
#define IDC_EDIT_DRAWUPPLANNINGINPUT    591
#define IDC_HOUSEProjectCode            592
#define IDC_EDIT_PROJECTDM              593
#define IDC_RADIO_HEIGHTNVQ             594
#define IDC_RADIO_HEIGHTTJ              595
#define IDC_RADIO_DC                    596
#define IDC_RADIO_HEIGHTDC              596
#define IDC_EDITMEASUREMETHOD           597
#define IDC_EDITBUILDAREAMEASURE        598
#define IDC_EDITMEASUREREPORTMEASURE    599
#define IDC_RADIO_DXGXDTC               600
#define IDC_RADIO_TQCL                  601
#define IDC_EDIT_ENTYPT                 602
#define IDC_EDIT_JGCLTBH                603
#define IDC_EDIT_JZTRYDBJJLQK           604
#define IDC_BUTTON_STARTPT              605
#define IDC_BUTTON_ENDPT                606
#define IDC_EDIT_STARYPTX               607
#define IDC_EDIT_STARTPTY               608
#define IDC_EDIT_ENDXPT                 609
#define IDC_COMBO_TQGCXS                610
#define IDC_XMJBXXYDDW                  611
#define IDC_XMJBXXZJZMJ                 612
#define IDC_XMJBXXZS                    613
#define IDC_XMJBXXDSJZMJ                614
#define IDC_XMJBXXDXJZMJ                616
#define IDC_XMJBXXYWFX                  617
#define IDC_XMJBXXLXDH                  618
#define IDC_SQDWXXSXH                   620
#define IDC_SQDWXXSQRMC                 621
#define IDC_SQDWXXZJZL                  622
#define IDC_SQDWXXZJH                   623
#define IDC_SQDWXXSQRLX                 624
#define IDC_SQDWXXFRMC                  625
#define IDC_SQDWXXFRZJZL                626
#define IDC_SQDWXXFRZJH                 627
#define IDC_XMJBXXXMBH                  628
#define IDC_XMJBXXXMMC                  629
#define IDC_XMJBXXZLKZ                  630
#define IDC_XMJBXXQXDM                  631
#define IDC_XMJBXXYWLX                  632
#define IDC_COMBO_JRFACTOR              633
#define IDC_COMBO_SELECTSTYLE           634
#define IDC_COMBO_DOMAINNAME            635
#define IDC_EDIT_IMPORTBH               636
#define IDC_BUTTON_BEGINDRAW            637
#define IDC_EDIT_DOMAINHEIGHT           638
#define IDC_LIST_SETTINGHEIGHT          639
#define IDC_LIST_SETTINGBUILDBGINFO     640
#define IDC_EDIT_PLPROJECTCODE          1000
#define IDC_EDIT_PLPROJECTNAME          1001
#define IDC_EDIT_PLPROJECTADDRESS       1002
#define IDC_EDIT_PLBUILDCOMPANY         1003
#define IDC_EDIT_PLMEASURECOMPANY       1004
#define IDC_EDIT_PLIMPLEMENTCOMPANY     1005
#define IDC_EDIT_PLCOORSYSTEM           1006
#define IDC_EDIT_PLEVEATIONALSYSTEM     1007
#define IDC_EDIT_PIPELINECCCGYJXKWS     1008
#define IDC_EDIT_PIPELINEYYZLQK         1009
#define IDC_EDIT_PIPELINETGKZQK         1010
#define IDC_EDIT_PIPELINEXBCLJBQK       1011
#define IDC_EDIT_PIPELINEDXGXDTC        1012
#define IDC_EDIT_PIPELINEYGHXKBYZQK     1013
#define IDC_EDIT_PIPELINEQTXYSMDQK      1014
#define IDC_TAB_PIPEPANEL               1016
#define IDC_EDIT_PIPELINEPROJECTNAME    1018
#define IDC_EDIT_PIPELINEBUILDCOMPANY   1019
#define IDC_EDIT_PIPELINEPROJECTCODE    1020
#define IDC_EDIT_PIPELINEPROJECTADDRESS 1021
#define IDC_EDIT_PIPELINEMEANSURECOMPANY 1022
#define IDC_EDIT_PIPELINEIMPLEMENTCOMPANY 1023
#define IDC_EDIT_PIPELINEPROJECTDIR     1024
#define IDC_EDIT_PIPELINEEVEALATIONSYSTEM 1025
#define IDC_EDIT_PIPELINECOORSYSTEM     1026
#define IDC_EDIT_ROADPINGMIAN           1028
#define IDC_EDIT_ROADZONGDUANMIAN       1029
#define IDC_EDIT_ROADHENGDUANMIAN       1030
#define IDD_DIALOG_MODIFYROADPRO        1031
#define IDC_LIST_1                      1032
#define IDC_BUTTON_ADD                  1033
#define IDC_BUTTON_DEL                  1034
#define IDC_BUTTON_ADD2                 1035
#define IDC_BUTTON_DEL2                 1036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        501
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         641
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
